name: 'Serverless Deploy'
inputs:
  stage:
    required: true
    description: 'The serverless stage'
  aws-region:
    required: true
    description: 'The aws region used to authenticate with AWS'
  install:
    required: false
    default: 'true'
    description: whether to run npm install
  arch:
    required: false
    default: 'arm64'
  platform:
    required: false
    default: 'linux'
  build:
    required: false
    default: 'false'
    description: whether to run npm run build
  working-directory:
    required: false
    default: '.'
    description: where to run the commands
  sentry-auth-token:
    required: false
    default: ''
    description: for releasing sentry projects
runs:
  using: 'composite'
  steps:
    - name: Install NPM
      if: inputs.install == 'true'
      run: cd ${{ inputs.working-directory }} && npm install
      env:
        npm_config_arch: ${{ inputs.arch }}
        npm_config_platform: ${{ inputs.linux }}
      shell: bash
    - uses: ./.github/workflows/aws
      with:
        aws-region: ${{ inputs.aws-region }}
    - name: Do Build
      if: inputs.build == 'true'
      run: cd ${{ inputs.working-directory }} && npm run build
      shell: bash
    - name: Release to S3
      shell: bash
      run: |
        aws s3 sync dist/ s3://ugc-nextgen-widgets-ap-southeast-2/templates/utils/${{ inputs.stage }}/ --delete