name: Release
run-name: Release to ${{ inputs.environment || 'staging' }} by @${{ github.actor }}

permissions:
  contents: write
  packages: write
  issues: read
  pull-requests: write
  id-token: write

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to run deployment in"
        type: environment
        required: true
        default: staging

env:
  NODE_AUTH_TOKEN: ${{ secrets.STACKLA_BOT_GITHUB_TOKEN }}

jobs:
  release:
    concurrency:
      group: releases
      cancel-in-progress: true
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 23.6.0
      - name: Install
        run: npm ci
      - uses: ./.github/workflows/aws
        with:
          aws-region: ${{ vars.AWS_REGION }}
      - name: Build & Release
        run: |
          gh auth setup-git
          npx changeset version
          git config user.name "$(gh api user --jq '.name // .login')"
          git config user.email "$(gh api user --jq '"\(.id)+\(.login)@users.noreply.github.com"')"
          git add .
          git commit -m "chore: release [skip ci]" || true
          git push origin master
        env:
          GH_TOKEN: ${{ secrets.STACKLA_BOT_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.STACKLA_BOT_GITHUB_TOKEN }}
